name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read
    checks: write
    id-token: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Permissison
      run: chmod +x mvnw
    - name: Build
      run: ./mvnw -B compile
    - name: Test
      run: ./mvnw -B test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4.1.0
      if: always()
      with:
        report_paths: 'target/surefire-reports/TEST-*.xml'
      
